create table if not exists public.form_submissions (
  id bigint generated by default as identity primary key,
  form_type text not null,
  payload jsonb not null,
  submitted_at timestamptz not null default now()
);
